mongodb:
  DB_CASHFLOW: "mongodb"
  DRIVER: "motor"
  NAME: "absensi_karyawan"
  USER: "admin"
  PASSWORD: "admin"
  HOST: "localhost"
  PORT: 27017

project:
  projectPrefix: "/absensi_karyawan"
  projectName: "Absensi Karyawan"
  debug: True
  key: "947cc8d843ca3bb645de29568a47df70ef5f1985f39d820ec3456cb82754cd2c"
  algorithm: "HS256"
  tokenExpiredInMinutes: 60
  environment: "development"